#
# Guidelines:
# - Section names:
#   - are lower case
#   - multi-word names use dash ('-') separators as in 'compound-section-name'
#
[server]
    host = "0.0.0.0"        # address on which the server listens
    port = 8000             #  and port

[global]

    projects = [    # a list of canonical project names
        "last",
        "mast",
        "wfast",
        "past"
    ]

    stations = [
        "davis",            # Davis Instruments Vantage-Pro2 weather station
        "inside-arduino",   # Inside Arduino
        "outside-arduino",  # Outside Arduino
        "cyclope",          # The Cyclope seeing monitor
        "tessw",            # The TESS-W cloud-cover monitor
        "internal",         # A station that performs internal calculations
    ]

[location]                  # Geographical location (assumes all projects are in the same location)
    longitude = 35.041
    latitude = 30.053
    elevation = 415.4

[database]
    host = "last0"
    name = "last_operational"
    user = "ocs"
    password = "physics"
    schema = "sensors"

    #
    # Stations are data-sources, each potentially contributing one or more datums.
    # NOTE:
    #   - The station names are used below to define sensor data-sources
    #   - If not specified, enabled == false
    #
[stations.davis]
    # datums:
    #  barometer, inside_temperature, inside_humidity,
    #  outside_temperature, wind_speed, wind_direction,
    #  outside_humidity, rain_rate, uv, solar_radiation
    interface = "/dev/ttyUSB0"
    baud = 19200
    interval = 60
    enabled = true

[stations.inside-arduino]
    # datums:
    #   temperature_in, pressure_in, visible_lux_in,
    #   presence, flame, co2, raw_h2, raw_ethanol, voc
    interface = "/dev/ttyUSB1"
    baud = 115200
    interval = 60
    # enabled = true

[stations.outside-arduino]
    # datums:
    #   temperature_out, humidity_out, pressure_out,
    #   dew_point, visible_lux_out, ir_luminosity,
    #   wind_speed, wind_direction
    interface = "/dev/ttyACM1"
    baud = 115200
    interval = 60
    # enabled = true

[stations.cyclope]
    host = "x.y.z.w"
    port = 12345
    interval = 60
    # enabled = true

[stations.tessw]
    host = "x.y.z.w"
    port = 12345
    interval = 60
    # enabled = true

[stations.internal]
    enabled = true      # hardcoded, cannot be disabled
    interval = 10

#
# The following sections define sensors that contribute to the is_safe/unsafe decision.
# Each sensor contributes its is_safe/unsafe value.  The system is is_safe iff ALL the sensors are 'is_safe'.
# Sensors can be:
# - one-shot: ('nreadings' == 1, default if no 'nreadings'). Only the latest reading is considered
# - cumulative: ('nreadings' > 1).  A number of readings are remembered
#   - The sensor is 'is_safe' IFF all the readings are 'is_safe'
#   - If the sensor changes from 'unsafe' to 'is_safe' it will remain 'unsafe' for a 'settling' [seconds] period to
#      prevent jitter.  It will become is_safe ONLY if ALL readings are is_safe after the 'settling' period
#
# Sensor attributes:
# - 'source':       [station:value] where is it obtained from (e.g. davis:humidity)
# - 'nreadings':    [int]           how many readings are remembered (default: 1)
# - 'min', 'max':   [float, float)  the safety range.  (default: 'min' == 0)
#
[sensors.sun]           # The sun elevation [degrees]
    enabled = true
    source = 'internal:sun_elevation'
    dusk = -14.3 # [deg]
    dawn = -13.0 # [deg]

[sensors.humidity]      # relative humidity [percent]
    enabled = true
    max = 90
    source = "davis:inside_humidity"
    nreadings = 3
    settling = 600

[sensors.wind-speed]    # [km/h]
    enabled = true
    max = 40
    source = "davis:wind_speed"
    nreadings = 5
    settling = 800

[sensors.cloud-cover]   # [percent]
    enabled = true
    max = 45
    source = "tessw:cover"
    nreadings = 3
    settling = 600

[sensors.dew-point]     # [centigrades]
    enabled = true
    max = 15
    source = "davis:dewpoint"
    nreadings = 5
    settling = 600

#
# Projects may override sensor definitions, otherwise they'll get the defaults above
#
[last.sensors.wind-speed]
    enabled = true
    max = 35                                # LAST is more sensitive to wind-speed
    nreadings = 7                           # - needs more readings to decide if is_safe/unsafe
    source = "davis:wind_speed"             # - doesn't trust the davis station, prefers outside-arduino instead
    settling = 800                          # - wants more time to settle down when transfering from unsafe to is_safe
