[temperature_in]
min = 0.0  # degrees C
max = 100.0  # degrees C
source = "davis_vantage"
interval = 60  # s
total_time = 600  # s

[temerature_out]
min = 0.0  # degrees C
max = 100.0  # degrees C
source = "davis_vantage"
interval = 60  # s
total_time = 600  # s

[wind_speed]
min = 0.0  # km/hr
max = 30.0  # km/hr
source = "davis_vantage"
interval = 30  # s
total_time = 900  # s